# Generated by Django 3.1.4 on 2020-12-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='toppings',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='detail',
            field=models.TextField(default=' ', max_length=1000),
        ),
    ]
