# Generated by Django 3.1.4 on 2021-01-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
